########################################################################################
#Tie Ma
#Student number 1537905
#class 439
#homework 2
########################################################################################
#Clean the enviroment
rm(list = ls())
dev.off()

#set the direction
setwd("~/SynologyDrive/nn/ECON-493-forcasting-economy/493 homework/homework 2")

#create a new file for all the generated by the graphic content
dir.create("pics")
#create a new file for all the data 
dir.create("pics")

#Lode the all package that necessary.
#some of the package may not been used in this homework
library("ggplot2")
library("fpp2")
library("glmnet")
library("tidyr")
library("lmtest")
library("boot")

#doctor who blue 
col = "#003b6f"
########################################################################################
#Exercise 1

#1-a Based upon your estimated trend model, construct a point forecast for 2018Q4？

#predition intervals 
   #4*squart(8) = 8


#Exercise 3

#####
#3-a
#Estimate a linear model with seasonal dummies as predictors using data from 1990Q1 to 2004Q4. 
#Evaluate the residuals. Compute the AIC and BIC.

au_beer <- window(ausbeer, start = 1990, end = c(2004,4))

fit.beer_season <- tslm(au_beer ~ season)
#time serive find the linear relationship 
#using the both trend with season

checkresiduals(fit.beer_season)
#some shit you can copy from the book
#residentual are standard divition, the mean equal to zero shit

CV(fit.beer_season)
#CV         AIC        AICc         BIC       AdjR2 
#220.9687500 282.3726654 283.6770132 292.1288840   0.9007409 

AIC(fit.beer_season)
  #546.8521
BIC(fit.beer_season)
  #557.3238


######
#3-b
  #Estimate a linear model with a trend and seasonal dummies as predictors 
  #using data from 1990Q1 to 2004Q4. Evaluate the residuals. Compute the AIC and BIC.

fit.beer_season_trend <- tslm(au_beer ~ season + trend)

checkresiduals(fit.beer_season_trend)
#some shit you can copy from the book
#residentual are standard divition, the mean equal to zero shit

checkresiduals(fit.beer_season_trend)

CV(fit.beer_season_trend)
#CV         AIC        AICc         BIC       AdjR2 
#192.7542573 274.3067186 276.1733853 286.0141809   0.9164696 

AIC(fit.beer_season_trend)
#519.3477
BIC(fit.beer_season_trend)
#531.9138

######
#3-c
#the linear model with a seaosn and trend are better due to 
#smaller AIC and BIC

#######
#3-d
#Evaluate the predictive performance of 
#these models in the test set 2005Q1 to 2009Q4.
#Which model performs better?

test_set <- window(ausbeer, start = 2005, end = c(2009,4))
#If my math is correct, there are 20 data set. 

test_end <- 2009.75

pred = matrix(NA, nrow = 20, ncol = 3)
#pred <- matrix(rep(NA,80),20,4)
#create a matrix 20x4 and repite 80 times NA. 

#loop 
for(i in 1:20){ #this loop running 20 times
  start_data<- 2005 #the start_time set at 2005
  tmp1 <- start_data +(i-1)*.25 #the function that coculate the different
  tmp <- window(test_set, start_data, tmp1) 
  pred[i,1] <- window(test_set, tmp1+.25, tmp1+.25) # actual 
  # compute forecasts 
  pred[i,2] <- meanf(tmp, h = 1)$mean 
  pred[i,3] <- rwf(tmp, h = 1)$mean
}


################################################################################################################################################################################
#Q4

#Q4-a Plot the data and ﬁnd the regression model for Demand 
#with temperature as an explanatory variable. Why is there a
#positive relationship?

daily20 <- head(elecdaily,20)

model_one <- tslm(Demand ~ Temperature, data = daily20)
#the higher the temputre, people will spend more electricity on the
#keep them cooling

######
#Q4-b

model_one %>% residuals() %>% plot()
#plot(residuals(model_one))
#there is no trend? 

checkresiduals(model_one)
#there are the trend of the model


######
#Q4-c

evil <- forecast(model_one, newdata = pure_evil )
pure_evil <- data.frame(
  Temperature = c(35, 45)
)
print(evil)

#Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
#1       275.7146 245.2278 306.2014 227.5706 323.8586
#2       343.2868 310.3597 376.2140 291.2890 395.2846


######
#Q4-d


#####
#Q4-e
View(elecdaily)
evil_data = head(elecdaily, 216)
model_two <- tslm(Demand ~ Temperature, data = evil_data)
plot(model_two, data = evil_data)


#################################################################################################
#q-5

#########5-a

######## 
library(datasets)
library(forecast)
########
Huron<- window(LakeHuron, start=1875, end=1972)

#########
autoplot(Huron, col = "#003b6f") + xlab("Year") + ylab("depth")
########

# 5- b
#take of the year as the variale.
year <- time(Huron)

#fit a linear regression 
linear_regression_model <- tslm(Huron ~ year, data = Huron) 

#fit a piecewise linear trend

t.break1 <- 1915
t <- time(LakeHuron)

t1 <- ts(pmax(0, t-t.break1), start = 1940)

fit.pw <- tslm(LakeHuron ~ t + t1)


t.new <- t[length(t)] + seq(10)
t1.new <- t1[length(t1)] + seq(10) 
newdata <- data.frame("t" = t.new, "t1" = t1.new)
fcasts.pw <- forecast(fit.pw, newdata = newdata)


install.packages("benchmarkme")



