########################################################################################
#Tie Ma
#Student number 1537905
#class 439
#homework 2
########################################################################################
#Clean the enviroment
rm(list = ls())
dev.off()

#set the direction
setwd("~/SynologyDrive/nn/ECON-493-forcasting-economy/493 homework/homework 2")

#create a new file for all the generated by the graphic content
dir.create("pics")
#create a new file for all the data 
dir.create("pics")

#Lode the all package that necessary.
#some of the package may not been used in this homework
library("ggplot2")
library("fpp2")
library("glmnet")
library("tidyr")
library("lmtest")
library("boot")

#doctor who blue 
col = "#003b6f"
########################################################################################
#Exercise 1

#1-a Based upon your estimated trend model, construct a point forecast for 2018Q4？

#predition intervals 
   #4*squart(8) = 8

#Exercise 3

#####
#3-a
#Estimate a linear model with seasonal dummies as predictors using data from 1990Q1 to 2004Q4. 
#Evaluate the residuals. Compute the AIC and BIC.

au_beer <- window(ausbeer, start = 1992, end = c(2004,4))

fit.beer_season <- tslm(au_beer ~ season)
#time serive find the linear relationship 
#using the both trend with season

checkresiduals(fit.beer_season)
#some shit you can copy from the book
#residentual are standard divition, the mean equal to zero shit

CV(fit.beer_season)
#CV         AIC        AICc         BIC       AdjR2 
#220.9687500 282.3726654 283.6770132 292.1288840   0.9007409 

######
#3-b
  #Estimate a linear model with a trend and seasonal dummies as predictors 
  #using data from 1990Q1 to 2004Q4. Evaluate the residuals. Compute the AIC and BIC.

fit.beer_season_trend <- tslm(au_beer ~ season + trend)

checkresiduals(fit.beer_season_trend )
#some shit you can copy from the book
#residentual are standard divition, the mean equal to zero shit

CV(fit.beer_season_trend )
#CV         AIC        AICc         BIC       AdjR2 
#192.7542573 274.3067186 276.1733853 286.0141809   0.9164696 

######
#3-c
#the linear model with a seaosn and trend are better due to 
#smaller AIC and BIC

#######
#3-d
#Evaluate the predictive performance of 
#these models in the test set 2005Q1 to 2009Q4.
#Which model performs better?

au_beer_test <- window(ausbeer, start = 2005, end = c(2009,4))


evil <- matrix(NA, ncol = 3, nrow = 2)
evil[1,] <- accuracy(fit.beer_season_trend, data = au_beer_test)[,c(2,3,5)]
evil[2,] <- accuracy(fit.beer_season, data = au_beer_test)[,c(2,3,5)]
rownames(evil) <- c("fit.beer_season_trend", "fit.beer_season")
colnames(evil) <- c("RMSE","MAE","MAPE")
print(evil)

#                        RMSE       MAE     MAPE
#fit.beer_season_trend 12.45572  9.639053 2.208542
#fit.beer_season       13.72155 10.195266 2.317054

#########

beer2 <- window(ausbeer, start = 1992, end = c(2007,4)) # training set
beer3 <- window(ausbeer, start = 2008)
tab <- matrix(NA, ncol = 3, nrow = 3)
 beerfit1 <- meanf(beer2, h = 10)
 beerfit2 <- rwf(beer2, h = 10)
 beerfit3 <- snaive(beer2, h = 10)
tab[1,] <- accuracy(beerfit1, beer3)[2,c(2,3,5)]
tab[2,] <- accuracy(beerfit2, beer3)[2,c(2,3,5)]
tab[3,] <- accuracy(beerfit3, beer3)[2,c(2,3,5)]
colnames(tab) <- c("RMSE","MAE","MAPE")
rownames(tab) <- c("Mean method", "Naïve method", "Seasonal naïve method")
tab

################################################################################################################################################################################
#Q4
########################################################################################

#Q4-a 
daily20 <- head(elecdaily,20)

