########################################################################################
#Tie Ma
#Student number 1537905
#class 439
#homework 2
########################################################################################
#Clean the enviroment
rm(list = ls())
dev.off()

#set the direction
setwd("~/SynologyDrive/nn/ECON-493-forcasting-economy/493 homework/homework 2")

#create a new file for all the generated by the graphic content
dir.create("pics")
#create a new file for all the data 
dir.create("pics")

#Lode the all package that necessary.
#some of the package may not been used in this homework
library("ggplot2")
library("fpp2")
library("glmnet")
library("tidyr")
library("lmtest")
library("boot")

#doctor who blue 
col = "#003b6f"
########################################################################################
#Exercise 1

#1-a Based upon your estimated trend model, construct a point forecast for 2018Q4？

#predition intervals 
   #4*squart(8) = 8

#Exercise 3

#####
#3-a
#Estimate a linear model with seasonal dummies as predictors using data from 1990Q1 to 2004Q4. 
#Evaluate the residuals. Compute the AIC and BIC.

au_beer <- window(ausbeer, start = 1992, end = c(2004,4))

fit.beer_season <- tslm(au_beer ~ season)
#time serive find the linear relationship 
#using the both trend with season

checkresiduals(fit.beer_season)
#some shit you can copy from the book
#residentual are standard divition, the mean equal to zero shit

CV(fit.beer_season)
#CV         AIC        AICc         BIC       AdjR2 
#220.9687500 282.3726654 283.6770132 292.1288840   0.9007409 

######
#3-b
  #Estimate a linear model with a trend and seasonal dummies as predictors 
  #using data from 1990Q1 to 2004Q4. Evaluate the residuals. Compute the AIC and BIC.

fit.beer_season_trend <- tslm(au_beer ~ season + trend)

checkresiduals(fit.beer_season_trend )
#some shit you can copy from the book
#residentual are standard divition, the mean equal to zero shit

CV(fit.beer_season_trend )
#CV         AIC        AICc         BIC       AdjR2 
#192.7542573 274.3067186 276.1733853 286.0141809   0.9164696 

######
#3-c
#the linear model with a seaosn and trend are better due to 
#smaller AIC and BIC

#######
#3-d
#Evaluate the predictive performance of 
#these models in the test set 2005Q1 to 2009Q4.
#Which model performs better?

au_beer_test <- window(ausbeer, start = 2005, end = c(2009,4))


evil <- matrix(NA, ncol = 3, nrow = 2)
evil[1,] <- accuracy(fit.beer_season_trend, data = au_beer_test)[,c(2,3,5)]
evil[2,] <- accuracy(fit.beer_season, data = au_beer_test)[,c(2,3,5)]
rownames(evil) <- c("fit.beer_season_trend", "fit.beer_season")
colnames(evil) <- c("RMSE","MAE","MAPE")
print(evil)

#                        RMSE       MAE     MAPE
#fit.beer_season_trend 12.45572  9.639053 2.208542
#fit.beer_season       13.72155 10.195266 2.317054


################################################################################################################################################################################
#Q4


#Q4-a 
daily20 <- head(elecdaily,20)
#note ths is a matrix!



#view the data 
View(daily20)
plot(daily20)

#There are two variable
  #demand
  #tempurtury

model_one <- lm(Demand ~ Temperature, data = daily20)

######
#Q4-b
checkresiduals(model_one)
#there are the trend of the model

######
#Q4-c
summary(model_one)

#Coefficients:
              #Estimate Std. Error t value Pr(>|t|)    
#(Intercept)  39.2117    17.9915   2.179   0.0428 *  
#Temperature   6.7572     0.6114  11.052 1.88e-09 ***
  ---
#Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

#Residual standard error: 22 on 18 degrees of freedom
#Multiple R-squared:  0.8716,	Adjusted R-squared:  0.8644 
#F-statistic: 122.1 on 1 and 18 DF,  p-value: 1.876e-09

#we can get the function
# y = 39.2117 + 6.7572x 

eq = function(x){39.2117 + 6.7572*x}

#forcasting one: when the temputure equal 15 degree. 

x1 <- 15
y  <- eq(x1)
print(y)
#the demand = 140.5697

#forcasting two: when the temperature equal to 35 degree.
x2 <- 34
y  <- eq(x2)
print(y)
#the demand = 268.9565

#yes, it mmarch with th e common sence.
#the higher the temperature, the more power people will use for the
#make the tempture cold and 15 degree is relatie less uncomforatable
#compare with 34 degree to force people to use air condition.

######
#Q4-d

predict(model_one, daily20)


#####
#Q5-e



#################################################################################################
#q-5

#5-a
install.packages(datasets)
library(datasets)
library(forecast)

Huron<- window(LakeHuron, start=1875, end=1972)
plot(Huron, col = "#003b6f")

# 5- b
evil <- time(Huron)
model_one_linear_regression <- tslm(Huron ~ evil , data = Huron) 

time_know <- 1915
evil_1 <- ts(pmax(0, evil - time_know), start = 1940)
piecewise_linear_model <- tslm(Huron ~ evil + evil_1)
evil.new <- t[length(evil)] + seq(10)
evil_1.new <
